# Тег
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

# Ингредиент
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

# Рецепт
RECIPE_NAME_MAX_LENGTH = 256
COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 32000

# Количество ингредиента в рецепте
AMOUNT_MIN = 1
AMOUNT_MAX = 32000

# Короткая ссылка
SHORT_CODE_LENGTH = 8

# Пагинация
DEFAULT_PAGE_SIZE = 6
